spring:
  datasource:
    url: jdbc:mysql://localhost:3306/halla?serverTimezone=Asia/Seoul
    username: halla
    password: halla
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100 #100? ?? ????? ????? ?? in ???? ??
    open-in-view: false #Transaction ???? ? repository? service???? ??? ????? ???? controller? ?? ??
    #?? ???? ??? API? OSIV? ??, ADMIN ?? ???? ?? ???? ?? ???? OSIV? ??.

logging.level:
  org.hibernate.sql: debug
